modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="horizonrpmod"
version="1.0.1"
displayName="Horizon Rp Mod"
displayURL="https://social.mtdv.me/blog/posts/horizonrpstory"
logoFile="logo.png"
credits="Roguen took 20 minutes to draw a disc and still didnt"
authors="Alkia, Roguen"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.horizonrpmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



